apiVersion: v2
appVersion: 3.89.0
deprecated: true
description: Nexus Repository Manager 3 Singleâ€‘Instance Helm Chart
home: https://www.sonatype.com/nexus-repository-oss
icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
- quickstart
- ci
- repository-manager
- nexus3
name: nexus-repository-manager
sources:
- https://github.com/sonatype/nexus-public
type: application
version: 88.3.0
